var port = 3000;
var connection = "localhost";
const DATA = new Array();
const CONNECTION_STRING = new Array();
const UPSTREAM = new Array();
const ARP = new Array();
const UPSTREAM_REMOTE = new Array();
console.log('teste de conexao...' + port);
console.log('teste arp...' + ARP);
console.log('teste de conexao...' + UPSTREAM_REMOTE);
console.log('teste de string de conexão...' + CONNECTION_STRING);